# Basic
name:               "Li-OmicsLab"
title:              "Li-OmicsLab at the Macao Polytechnic University"
description:        "Li-OmicsLab is a research group of Macao Polytechnic University based on multi-omics research on the pathogenesis of complex chronic diseases, discovery of new drug targets, drug mechanism of action, and toxicological evaluation applications."

# URL
url:                https://github.com/Li-OmicsLab
baseurl:
wwwurl:             http://liomicslab.net

#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "blog"
    href:           "/blog"
  - name:           "resources"
    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
